FROM debian:unstable
RUN apt update -y
RUN apt install -y cmake g++ qtbase5-dev qtmultimedia5-dev libpjproject-dev
ADD . /usr/src/ktelephone
WORKDIR /usr/src/ktelephone
RUN mkdir -p build/
WORKDIR /usr/src/ktelephone/build
RUN cmake ..
RUN make
RUN mkdir -p /export && \
    cp /usr/src/ktelephone/build/ktelephone /export/ && \
    ldd /usr/src/ktelephone/build/ktelephone | grep "=> /" | awk '{print $3}' | \
    xargs -I{} cp {} /export/ && \
    cp -r /usr/src/ktelephone/build/data /export/
