FROM debian:unstable
RUN apt update -y
RUN apt install -y cmake g++ qtbase5-dev qtmultimedia5-dev libpjproject-dev
ADD . /usr/src/ktelephone
WORKDIR /usr/src/ktelephone
RUN mkdir -p build/
WORKDIR /usr/src/ktelephone/build
RUN cmake ..
RUN make
